### .bash_profile --- sourced by login shells, not sourced by interactive shells.

### The .bash_profile is sourced automatically in a login shell, for example, when a user logs in to the Openmind head node or logs in to a compute node using ssh nodeXXX.

### The .bashrc is sourced automatically in a non-login shell, for example, when a user executes bash or gets on an interactive section using srun --pty bash or submits a batch job script using sbatch job.sh (if there is the first line #!/bin/bash in the job script).

### $HOME/.bashrc has a line that sources /etc/bashrc, which is necessary for CentOS 7 / Rocky 8 cross-compatibility, so it's sourced here:

echo "LOADING .bash_profile"
echo "Current SHELL: $0"

if [ -f $HOME/.bashrc ]; then
    source $HOME/.bashrc
fi

### For Astral UV and UVX ###
### adds $HOME/.local/bin to PATH (if not already there), which is where Astral UV and UVX are installed
# if [ -f /etc/bashrc ]; then
#   . "$HOME/.local/bin/env"
# fi
