### The .bash_profile is sourced automatically in a login shell, for example, when a user logs in to the Openmind head node or logs in to a compute node using ssh nodeXXX.

### The .bashrc is sourced automatically in a non-login shell, for example, when a user executes bash or gets on an interactive section using srun --pty bash or submits a batch job script using sbatch job.sh (if there is the first line #!/bin/bash in the job script).

### these print commands break rsync
# echo "LOADING .bashrc"
# echo "Current SHELL: $0"

### The new OS Rocky 8 is installed on the new nodes (>=100), while the old OS CentOS 7 is used on the old nodes (<100). In order to make applications work smoothly on both OS, especially to resolve the issues related to module, add the following lines in the .bashrc file in your home directory.

if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

source $HOME/.merc

#export PATH=$HOME/local/bin:$PATH
#export PATH=/home/daeda/me/zsh/bin:/home/daeda/me/git/bin:$PATH
. "$HOME/.local/bin/env"